server:
  port: ${PORT:8080}

spring:
  jpa:
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  cache:
    redis:
      time-to-live: 600000

logging:
  level:
    com.gatherup: INFO
    root: WARN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
